[package]
name = "proj17_iot-server"
version = "0.0.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
appsody-rocket = { path = ".appsody" }
rocket = "0.4.2"
futures = "0.3.4"
mysql = "*"

[[bin]]
name = "proj17_iot-server"
path = "src/main.rs"